version: "3.8"

services:
  go:
    image: golang:1.20-alpine
    container_name: go-app
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    command: go run main.go
    depends_on:
      - db

  react:
    image: node:18-alpine
    container_name: react-app
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - go

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
